project:
  type: website
  output-dir: "docs"

website:
  title: "Seydou TOGUIYENI"
  navbar:
    left: 
      - text: "Home"
        file : index.qmd
      - text: "Portfolio"
        file : portfolio.qmd
      - text: "CV"
        file : cv.qmd
    right:
      - icon: github
        href: https://github.com/mtoguiyeni
      - icon: twitter
        href: https://twitter.com/toguiyeni
      - icon: linkedin
        href: https://www.linkedin.com/in/seydou-toguiyeni-a6a8aa112/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

